name: rada-deployment

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    expose:
      - "8443"  # Only expose to internal network
    environment:
      - NODE_ENV=production
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - ./backend/.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - rada-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate -q --spider https://localhost:8443/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    ports:
      - "80:80"    # HTTP port
      - "443:443"  # HTTPS port
    environment:
      - NGINX_DOMAIN=${DOMAIN_NAME}
      - VITE_BACKEND_URL=https://${DOMAIN_NAME}/api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rada-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  rada-network:
    driver: bridge
