version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
