version: "3.8"

services:
  backend:
    build:
      context: https://catchshyam@bitbucket.org/catchshyam/rada-backend.git#main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: https://catchshyam@bitbucket.org/catchshyam/rada-frontend-ts.git#main
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
