name: rada-deployment

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      ssh:
        - source=default
      args:
        CACHE_DATE: ${CACHE_DATE:-}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      ssh:
        - source=default
      args:
        CACHE_DATE: ${CACHE_DATE:-}
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
