name: rada-deployment

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      ssh:
        - default=/home/ec2-user/.ssh/id_ed25519
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
